inherit_from: .rubocop_todo.yml

Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/FileName:
 Exclude:
   - lib/rubocop-bugcrowd.rb

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
   - spec/**/*.rb
