inherit_from: .rubocop_todo.yml

Naming/FileName:
 Exclude:
   - lib/rubocop-bugcrowd.rb

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
   - spec/**/*.rb

Layout/LineLength:
  Max: 100
