# Write it!

# Foobar/SuperCoolCopNamze:
#   Description: 'TODO: Write a description of the cop.'
#   Enabled: pending
#   VersionAdded: '0.80'

Bugcrowd/ReplicaIdentityRequired:
  Description: 'Checks that tables have a replica identity defined'
  Enabled: pending
  VersionAdded: '0.80'

Bugcrowd/VisitInSpecBeforeHook:
  Description: "Avoid using 'visit' in before hooks, as it creates strict order dependencies that are hard to untangle"
  Include:
    - 'spec/features/**/*.rb'
    - 'spec/system/**/*.rb'
  Enabled: true

Bugcrowd/CurrentJumpingControllerBoundary:
  Description: 'Catches Current jumping controller boundaries'
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
    - 'app/controllers/**/*.rb'

Bugcrowd/AddIndexNonConcurrently:
  Description: 'Always add indexes concurrently'
  Include:
    - 'db/migrate/*.rb'
  Enabled: true

Bugcrowd/DangerousEnvMutation:
  Description: 'Prevent direct modification of ENV to prevent global state pollution'
  Include:
    - 'spec/**/*.rb'
  Exclude:
    - 'spec/spec_helper.rb'
  Enabled: true

Bugcrowd/PreferRequestYieldingResponsePattern:
  Description: 'Prefer request_yielding_response pattern for request specs'
  Include:
    - 'spec/requests/**/*.rb'
  Enabled: true

Bugcrowd/PreferSensibleStringEnum:
  Description: 'Prefer SensibleStringEnum over built in Rails enum'
  Enabled: true

Bugcrowd/RailsConfigurationMutation:
  Description: 'Prevent direct modification of Rails config to prevent global state pollution'
  Include:
    - 'spec/**/*.rb'
  Exclude:
    - 'spec/spec_helper.rb'
  Enabled: true

Bugcrowd/RequireOptionalForBelongsTo:
  Description: 'blah'
  Include:
    - 'app/models/**/*.rb'
  Enabled: true

Bugcrowd/DangerousTransaction:
  Description: Prefer ProperTransaction.start to custom transactions
  Enabled: true
  VersionAdded: '0.80'

Bugcrowd/AvoidSampleInSpecs:
  Description: Avoid using sample in spec as it can cause non-deterministic behavior
  Enabled: true
  Include:
    - 'spec/**/*.rb'
