# Write it!

# Foobar/SuperCoolCopNamze:
#   Description: 'TODO: Write a description of the cop.'
#   Enabled: pending
#   VersionAdded: '0.80'

Bugcrowd/CurrentJumpingControllerBoundary:
  Description: 'Catches Current jumping controller boundaries'
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
    - 'app/controllers/**/*.rb'
